# Generated by Django 3.2.3 on 2021-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211105_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
