# Generated by Django 3.2.3 on 2022-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmenu',
            name='breakfast_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='dinner_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='messmenu',
            name='lunch_price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
